### ISSUE TITLE
Problems polling different kind of string objects (pyasn1?)

### ISSUE THREAD

**Issue by kaihil** [etingof/pysnmp#73] opened 2017-08-09 14:13 UTC
Hi,

I experienced some problems when polling string data with pysnmp.

I experienced also altering behavior when changing the following parameters:
a) the pyasn1 version (0.3.2 vs. 0.2.3)
b) the polled object (sysDescr vs. ifName)
c) the type of naming the object (Object Name vs. OID)

I tried to reproduce it somehow with pysnmp-apps and experienced this erroneous and strange behavior. At least for me it makes no sense ;) The following matrix shows, which combinations work and which doesn't.

Short:
* Case sysDescr
  * pyasn1==0.3.2, via Object Name: :x:
  * pyasn1==0.3.2, via OID: :x:
  * pyasn1==0.2.3, via Object Name: 💚 
  * pyasn1==0.2.3, via OID: 💚 
* Case get ifName
  * pyasn1==0.3.2, via Object Name: :x:
  * pyasn1==0.3.2, via OID: :x:
  * pyasn1==0.2.3, via Object Name: 💚 
  * pyasn1==0.2.3, via OID: :x:

# Prerequisites
## env1:
```
$ pip install pysnmp-apps
$ pip freeze
ply==3.10
pyasn1==0.3.2
pycryptodome==3.4.6
pysmi==0.1.3
pysnmp==4.3.9
pysnmp-apps==0.4.1
```
## env2:
```
$ pip install pyasn1==0.2.3
$ pip install pysnmp-apps
$ pip freeze
ply==3.10
pyasn1==0.2.3
pycryptodome==3.4.6
pysmi==0.1.3
pysnmp==4.3.9
pysnmp-apps==0.4.1
```

# Case sysDescr
```
$ snmpget -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com SNMPv2-MIB::sysDescr.0
SNMPv2-MIB::sysDescr.0 = STRING: Linux zeus 4.8.6.5-smp #2 SMP Sun Nov 13 14:58:11 CDT 2016 i686
$ snmpget -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com 1.3.6.1.2.1.1.1.0
SNMPv2-MIB::sysDescr.0 = STRING: Linux zeus 4.8.6.5-smp #2 SMP Sun Nov 13 14:58:11 CDT 2016 i686
```
```
(env1) $ snmpget.py -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com SNMPv2-MIB::sysDescr.0
=> crash (for error output see below)
(env1) $ snmpget.py -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com 1.3.6.1.2.1.1.1.0
=> crash (for error output see below)
```
```
(env2) $ snmpget.py -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com SNMPv2-MIB::sysDescr.0
SNMPv2-MIB::sysDescr.0 = DisplayString: Linux zeus 4.8.6.5-smp #2 SMP Sun Nov 13 14:58:11 CDT 2016 i686
(env2) $ snmpget.py -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com 1.3.6.1.2.1.1.1.0
SNMPv2-MIB::sysDescr.0 = DisplayString: Linux zeus 4.8.6.5-smp #2 SMP Sun Nov 13 14:58:11 CDT 2016 i686
```

# Case ifName

```
$ snmpget -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com IF-MIB::ifName.1
IF-MIB::ifName.1 = STRING: lo
$ snmpget -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com 1.3.6.1.2.1.31.1.1.1.1.1
IF-MIB::ifName.1 = STRING: lo
```
```
(env1) $ snmpget.py -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com IF-MIB::ifName.1
=> crash (for error output see below)
(env1) $ snmpget.py -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com 1.3.6.1.2.1.31.1.1.1.1.1
=> crash (for error output see below)
```
```
(env2) $ snmpget.py -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com IF-MIB::ifName.1
IF-MIB::ifName."1" = DisplayString: lo
(env2) $ snmpget.py -v3 -u usr-md5-des -l authPriv -A authkey1 -X privkey1 demo.snmplabs.com 1.3.6.1.2.1.31.1.1.1.1.1
=> crash (for error output see below)
```

# Example log (from first command)

```
Error: poll error: Traceback (most recent call last):
;  File "/Users/kaihil/pysnmp-test/env1/lib/python3.5/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
;  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 188, in poll2
    readwrite(obj, flags)
;  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
;  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
;  File "/Users/kaihil/pysnmp-test/env1/lib/python3.5/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 163, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
;  File "/Users/kaihil/pysnmp-test/env1/lib/python3.5/site-packages/pysnmp/carrier/base.py", line 70, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
;  File "/Users/kaihil/pysnmp-test/env1/lib/python3.5/site-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
;  File "/Users/kaihil/pysnmp-test/env1/lib/python3.5/site-packages/pysnmp/proto/rfc3412.py", line 486, in receiveMessage
    cachedParams['cbCtx'])
;  File "/Users/kaihil/pysnmp-test/env1/lib/python3.5/site-packages/pysnmp/entity/rfc3413/cmdgen.py", line 139, in processResponsePdu
    cbFun(snmpEngine, origSendRequestHandle, None, PDU, cbCtx)
;  File "/Users/kaihil/pysnmp-test/env1/lib/python3.5/site-packages/pysnmp/entity/rfc3413/cmdgen.py", line 207, in processResponseVarBinds
    PDU and v2c.apiPDU.getVarBinds(PDU) or (), cbCtx)
;  File "/Users/kaihil/pysnmp-test/env1/bin/snmpget.py", line 57, in cbFun
    cbCtx['mibViewController'], oid, val
;  File "/Users/kaihil/pysnmp-test/env1/lib/python3.5/site-packages/pysnmp_apps/cli/mibview.py", line 402, in getPrettyOidVal
    out = out + syntax.prettyOut(val)
;  File "<string>", line 176, in prettyOut
;  File "/Users/kaihil/pysnmp-test/env1/lib/python3.5/site-packages/pysnmp/proto/rfc1902.py", line 229, in prettyOut
    return octets.octs2str(value)
;  File "/Users/kaihil/pysnmp-test/env1/lib/python3.5/site-packages/pyasn1/compat/octets.py", line 40, in <lambda>
    octs2str = lambda x: x.decode('iso-8859-1')
;AttributeError: 'OctetString' object has no attribute 'decode'

Usage: /Users/kaihil/pysnmp-test/env1/bin/snmpget.py [OPTIONS] <AGENT> <PARAMETERS>
Command-line SNMP tools version 0.4.1, written by Ilya Etingof <ilya@glas.net>
Foundation libraries: pysmi 0.1.3, pysnmp 4.3.9, pysnmp-mibs N/A, pyasn1 0.3.2
Python interpreter: 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
(...)
```

**Comment by etingof** [comment] 2017-08-09 14:28
Thank you for your report!

I can confirm the issue when running with Python 3, but not with Python 2. From the brief glance, it seems to be specific to the `snmpget.py` tool because functionally similar stand-alone [code snippet](http://pysnmp.sourceforge.net/examples/hlapi/asyncore/sync/manager/cmdgen/snmp-versions.html#snmpv3-auth-md5-privacy-des) seems to work for me.

I expect to come up with a fix shortly.

**Comment by kaihil** [comment] 2017-08-09 14:41
Thanks for your quick response :)

When I do the same with `snmpbulkwalk.py` (using the corresponding parent objects) i get this result for the matrix:
* Case sysDescr
  * pyasn1==0.3.2, via Object Name: :x:
  * pyasn1==0.3.2, via OID: :x:
  * pyasn1==0.2.3, via Object Name: 💚 
  * pyasn1==0.2.3, via OID: 💚 
* Case get ifName
  * pyasn1==0.3.2, via Object Name: :x:
  * pyasn1==0.3.2, via OID: :x:
  * pyasn1==0.2.3, via Object Name: 💚 
  * pyasn1==0.2.3, via OID: 💚  *this case doesn't work for `snmpget.py`*

At least the last case now works. But it still doesn't work for pyasn1 0.3.2 at all.

**Comment by etingof** [comment] 2017-08-09 17:57
This should be fixed in [pysnmp-apps master](https://github.com/etingof/pysnmp-apps/commit/b81d275e8686eace5c57f421f6378c9b44f29a4f). You are welcome to test it before it's released. ;-)

**Comment by etingof** [comment] 2017-08-09 19:31
pysnmp-apps-0.4.2 has been released on PyPI

**Closed by etingof** 2017-08-09 19:31 UTC
Labels: bug

**Comment by kaihil** [comment] 2017-08-10 07:45
I can confirm that it works now. Thanks a lot @etingof!
