### ISSUE TITLE
Malformed ObjectType when polling CISCO-BGP4-MIB::cbgpPeer2Table

### ISSUE THREAD

**Issue by kaihil** [etingof/pysnmp#74] opened 2017-08-10 12:14 UTC
Hi!
I have problems polling the SNMP table `CISCO-BGP4-MIB::cbgpPeer2Table`. The `ObjectType` instance seems to be malformed when the object identifier contains ipv6 data (i.e. `InetAddressType` is `'ipv6'` and `InetAddress` contains a ipv6 address). That leads to some kind of Exception in prettyPrint() (see below).

The error occurs on the latest pysnmp 4.3.9, but not on 4.3.5 (with pyasn1==0.2.3). I think it was introduced in pysnmp 4.3.6, but i'm not sure.

I attached an example script performing a simple bulkwalk on `CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt`. A minimal `public.snmp_rec` file for "snmpsim" and the corresponding MIB file are also attached. [bgp-example.bulkwalk.zip](https://github.com/etingof/pysnmp/files/1214829/bgp-example.bulkwalk.zip)

# Prerequisites
## env435:
```
$ pip install pyasn1==0.2.3 pysnmp==4.3.5 pysnmp-mibs
$ pip freeze
ply==3.10
pyasn1==0.2.3
pycryptodome==3.4.6
pysmi==0.1.3
pysnmp==4.3.5
pysnmp-mibs==0.1.6
```
## env439:
```
$ pip install pysnmp pysnmp-mibs
$ pip freeze
ply==3.10
pyasn1==0.3.2
pycryptodome==3.4.6
pysmi==0.1.3
pysnmp==4.3.9
pysnmp-mibs==0.1.6
```

# Running the example script

When I use pysnmp 4.3.5 and pyasn1 0.2.3 the script works as expected:
```
(env435) $ python bgp-example-bulkwalk.py
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80101 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80102 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80103 = peer unconfigured
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80104 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80105 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80106 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80107 = peer unconfigured
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80108 = peer unconfigured
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80109 = peer unconfigured
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a8010a = administrative shutdown
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv6'.0x2a014860000100010000000000000064 = peer unconfigured
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv6'.0x2a014860000100010000000000000065 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv6'.0x2a014860000100010000000000000066 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv6'.0x2a014860000100010000000000000067 = hold time expired
```

But when i use the latest pysnmp 4.3.9 with the latest pyasn1 0.3.2 it throws an exception:
```
(env439) $ python bgp-example-bulkwalk.py
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80101 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80102 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80103 = peer unconfigured
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80104 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80105 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80106 = hold time expired
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80107 = peer unconfigured
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80108 = peer unconfigured
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a80109 = peer unconfigured
CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.'ipv4'.0xc0a8010a = administrative shutdown
Traceback (most recent call last):
  File "bgp-example-bulkwalk.py", line 31, in <module>
    print(' = '.join([x.prettyPrint() for x in varBind]))
  File "bgp-example-bulkwalk.py", line 31, in <listcomp>
    print(' = '.join([x.prettyPrint() for x in varBind]))
  File "/Users/kaihil/pysnmp-test/env439/lib/python3.5/site-packages/pysnmp/smi/rfc1902.py", line 532, in prettyPrint
    '.'.join([x.isSuperTypeOf(s) and '"%s"' % x.prettyPrint() or x.prettyPrint() for x in self.__indices])
  File "/Users/kaihil/pysnmp-test/env439/lib/python3.5/site-packages/pysnmp/smi/rfc1902.py", line 532, in <listcomp>
    '.'.join([x.isSuperTypeOf(s) and '"%s"' % x.prettyPrint() or x.prettyPrint() for x in self.__indices])
AttributeError: 'tuple' object has no attribute 'isSuperTypeOf'
```

**Comment by etingof** [comment] 2017-08-11 16:40
Thank you for your report! Just a quick note that I'm on it and hopefully fix it in the upcoming 4.3.10

**Comment by etingof** [comment] 2017-08-11 20:55
I believe this crash has been fixed in this [pre-release branch](https://github.com/etingof/pysnmp/tree/release-4.3.10).

The root cause, though, is that either the

    CISCO-BGP4-MIB::cbgpPeer2LastErrorTxt.16.42.1.72.96.0.1.0.1.0.0.0.0.0.0.0.100

OID is malformed (in .snmprec) and can't be broken down onto individual SNMP table indices or it's another bug in pysnmp (I will look into that to make sure).

If you enable pysnmp debugging and grep for `error resolving table indices` you will see the exact error.

**Comment by etingof** [comment] 2017-08-12 22:22
Alright, it turned out to be pysnmp problem. Please try [this branch](https://github.com/etingof/pysnmp/tree/release-4.3.10), your script works for me with it.

**Comment by kaihil** [comment] 2017-08-14 11:58
Hey, i gave it a short try and it seem to work, thanks!

**Comment by etingof** [comment] 2017-10-14 11:59
pysnmp 4.3.10 has been released on PyPI

**Closed by etingof** 2017-10-14 11:59 UTC
