### ISSUE TITLE
Some OIDS skipped when using nextCmd

### ISSUE THREAD

**Issue by fried-sausage** [etingof/pysnmp#253] opened 2019-04-02 14:42 UTC
I run snmpsim (from venv) like this: `snmpsimd.py --agent-udpv4-endpoint=127.0.0.1:1024`

Then i run code below on the same machine:
```python3
from pysnmp.hlapi import *


START_OID = '1.3.6'  # '1.3.6.1.4'
ADDR = ('127.0.0.1', 1024)


for (errorIndication,
     errorStatus,
     errorIndex,
     varBinds) in nextCmd(SnmpEngine(),
                          CommunityData("public", mpModel=1),
                          UdpTransportTarget(ADDR),
                          ContextData(),
                          ObjectType(ObjectIdentity(START_OID)),
                          lexicographicMode=True):

    if errorIndication:
        print(errorIndication)
        break
    elif errorStatus:
        print('%s at %s' % (errorStatus.prettyPrint(),
                            errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
        break
    else:
        for varBind in varBinds:
            name, val = varBind
            print(name, val.prettyPrint())
```

Despite initial OID being `1.3.6`, i don't see any oids starting with `1.3.6.1.4` in output. My output: https://gist.github.com/fried-sausage/af350a21b2f330efedbe3f7fd7032830

When i change START_OID   to `1.3.6.1.4`, however, i see several such oids: https://gist.github.com/fried-sausage/18af75011632083a2d952942c34a0f8f

Why are `1.3.6.1.4` oids skipped when i start from root? Is this expected behaviour?

**Comment by fried-sausage** [comment] 2019-04-02 14:56
snmpwalk behaves similarly, so probably there is something i don't understand.
`snmpwalk -v2c -On -c public 127.0.0.1:1024 .1.3`

**Comment by etingof** [comment] 2019-04-02 15:02
May be an error occurs somewhere half way towards the branch you want? Check it out in the snmpsimd logs/stdout.

Walking its public instance at `demo.snmplabs.com:161` with your command seems to work:

```
...
.1.3.6.1.2.1.2.2.1.20.2 = Counter32: 3828610
.1.3.6.1.2.1.2.2.1.21.1 = Gauge32: 4294967295
.1.3.6.1.2.1.2.2.1.21.2 = Gauge32: 4294967295
.1.3.6.1.2.1.3.1.1.1.2.1.195.218.254.97 = INTEGER: 2
.1.3.6.1.2.1.3.1.1.2.2.1.195.218.254.97 = Hex-STRING: 00 0E 84 9F 9C 19 
.1.3.6.1.2.1.3.1.1.3.2.1.195.218.254.97 = IpAddress: 195.218.254.97
.1.3.6.1.2.1.4.1.0 = INTEGER: notForwarding(2)
.1.3.6.1.2.1.4.2.0 = INTEGER: 64
.1.3.6.1.2.1.4.3.0 = Counter32: 22908563
.1.3.6.1.2.1.4.4.0 = Counter32: 0
```

**Comment by fried-sausage** [comment] 2019-04-02 15:08
.1.3.6.1.2.1.4
.1.3.6.1.4
The former is what you see now, the latter is what i wanted to see (translates to iso.org.dod.internet.private if im not mistaken)

**Comment by fried-sausage** [comment] 2019-04-02 15:24
Here is output of snmpsimd stderr: https://gist.github.com/fried-sausage/5ddc3aea70ff72f703938108c95d4e25
```
$ grep -I err stderr.txt
Variation module "error" from "/home/rob/snmp_managing_entity/simulator/venv/snmpsim/variation/error.py" loaded OK
    Configuring /home/rob/snmp_managing_entity/simulator/venv/snmpsim/data/variation/error.snmprec controller
    SNMPv1/2c community name: variation/error
    SNMPv3 Context Name: 83e5bd723f8095e1a27fb2b404e50404 or variation/error
ERROR data error at /home/rob/snmp_managing_entity/simulator/venv/snmpsim/data/public.snmprec controller for 1.3.6.1.2.1.11.13.0: dictionary update sequence element #0 has length 3; 2 is required
Variation module "error" shutdown OK
```
So there is an error, but it doesn't come from branch i expect.

**Comment by etingof** [comment] 2019-04-02 16:19
Perhaps that's caused by a missing comma:
```
1.3.6.1.2.1.11.14.0|65:numeric|rate=0.001cumulative=1
```
Should be fixed in the public instance as well.

**Comment by fried-sausage** [comment] 2019-04-02 16:29
This indeed fixed the issue. Thanks.

**Closed** 2019-04-03 11:46 UTC
